name: Checkstyle

on:
  pull_request:
    branches: [main, master, develop]

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.java

      - name: Run checkstyle on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if ! grep -q "<artifactId>maven-checkstyle-plugin</artifactId>" pom.xml; then
            sed -i '/<build>/a \
              <plugins>\
                <plugin>\
                  <groupId>org.apache.maven.plugins</groupId>\
                  <artifactId>maven-checkstyle-plugin</artifactId>\
                  <version>3.1.2</version>\
                  <configuration>\
                    <configLocation>checkstyle.xml</configLocation>\
                  </configuration>\
                </plugin>\
              </plugins>' pom.xml
          fi

          # Create a basic Checkstyle configuration file
          cat << EOF > checkstyle.xml
          <?xml version="1.0"?>
          <!DOCTYPE module PUBLIC
            "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
            "https://checkstyle.org/dtds/configuration_1_3.dtd">
          <module name="Checker">
            <module name="TreeWalker">
              <module name="AvoidStarImport"/>
              <module name="ConstantName"/>
              <module name="EmptyBlock"/>
              <module name="EmptyStatement"/>
              <module name="EqualsHashCode"/>
              <module name="MagicNumber"/>
              <module name="MethodLength"/>
              <module name="NestedIfDepth"/>
              <module name="NestedTryDepth"/>
              <module name="OneStatementPerLine"/>
              <module name="RedundantImport"/>
              <module name="SimplifyBooleanExpression"/>
              <module name="SimplifyBooleanReturn"/>
              <module name="UnusedImports"/>
              <module name="UpperEll"/>
            </module>
          </module>
          EOF

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.java ]]; then
              echo "Checking $file"
              # Run Maven Checkstyle plugin on the changed file
              mvn checkstyle:check \
                -Dcheckstyle.config.location=checkstyle.xml \
                -Dcheckstyle.includeResources=false \
                -Dcheckstyle.includeTestResources=false \
                -Dcheckstyle.violationSeverity=warning \
                -Dcheckstyle.maxAllowedViolations=0 \
                -Dcheckstyle.sourcePath=$file
            fi
          done

      - name: Check for Checkstyle errors
        if: failure()
        run: |
          echo "Checkstyle found errors. Please fix them before merging."
          exit 1
