name: OWASP Dependency-Check

# Trigger the workflow when pom.xml files are modified in a pull request
on:
  pull_request:
    paths:
      - '**/pom.xml'
      - 'pom.xml'

jobs:
  dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache OWASP Dependency-Check Data
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-owasp-dependency-check-data

      # Run OWASP Dependency-Check using Maven plugin
      - name: Run OWASP Dependency-Check
        run: |
          mvn org.owasp:dependency-check-maven:check \
            -DfailBuildOnCVSS=7 \
            -DfailOnError=true

      # Upload the Dependency-Check report as an artifact
      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Check Report
          path: target/dependency-check-report.html

      - name: Check for vulnerabilities
        run: |
          if grep -q "One or more dependencies were identified with known vulnerabilities" target/dependency-check-report.html; then
            echo "Critical vulnerabilities found. Please address them before merging."
            exit 1
          fi
